/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiAlertsSettingsRouteImport } from './routes/api/alerts-settings'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiCredentialsRouteImport } from './routes/api/credentials'
import { Route as ApiDisplayRouteImport } from './routes/api/display'
import { Route as ApiDisplayBackgroundRouteImport } from './routes/api/display-background'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHomesRouteImport } from './routes/api/homes'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiSeriesRouteImport } from './routes/api/series'
import { Route as ApiTouRouteImport } from './routes/api/tou'
import { Route as GraphsMetricRouteImport } from './routes/graphs/$metric'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsSettingsRoute = ApiAlertsSettingsRouteImport.update({
  id: '/api/alerts-settings',
  path: '/api/alerts-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCredentialsRoute = ApiCredentialsRouteImport.update({
  id: '/api/credentials',
  path: '/api/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplayRoute = ApiDisplayRouteImport.update({
  id: '/api/display',
  path: '/api/display',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplayBackgroundRoute = ApiDisplayBackgroundRouteImport.update({
  id: '/api/display-background',
  path: '/api/display-background',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomesRoute = ApiHomesRouteImport.update({
  id: '/api/homes',
  path: '/api/homes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesRoute = ApiSeriesRouteImport.update({
  id: '/api/series',
  path: '/api/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTouRoute = ApiTouRouteImport.update({
  id: '/api/tou',
  path: '/api/tou',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsMetricRoute = GraphsMetricRouteImport.update({
  id: '/graphs/$metric',
  path: '/graphs/$metric',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/graphs/$metric': typeof GraphsMetricRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/graphs/$metric': typeof GraphsMetricRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/graphs/$metric': typeof GraphsMetricRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/series'
    | '/api/tou'
    | '/graphs/$metric'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/series'
    | '/api/tou'
    | '/graphs/$metric'
  id:
    | '__root__'
    | '/'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/series'
    | '/api/tou'
    | '/graphs/$metric'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAlertsSettingsRoute: typeof ApiAlertsSettingsRoute
  ApiCostRoute: typeof ApiCostRoute
  ApiCredentialsRoute: typeof ApiCredentialsRoute
  ApiDisplayRoute: typeof ApiDisplayRoute
  ApiDisplayBackgroundRoute: typeof ApiDisplayBackgroundRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiHomesRoute: typeof ApiHomesRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiSeriesRoute: typeof ApiSeriesRoute
  ApiTouRoute: typeof ApiTouRoute
  GraphsMetricRoute: typeof GraphsMetricRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts-settings': {
      id: '/api/alerts-settings'
      path: '/api/alerts-settings'
      fullPath: '/api/alerts-settings'
      preLoaderRoute: typeof ApiAlertsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials': {
      id: '/api/credentials'
      path: '/api/credentials'
      fullPath: '/api/credentials'
      preLoaderRoute: typeof ApiCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/display': {
      id: '/api/display'
      path: '/api/display'
      fullPath: '/api/display'
      preLoaderRoute: typeof ApiDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/display-background': {
      id: '/api/display-background'
      path: '/api/display-background'
      fullPath: '/api/display-background'
      preLoaderRoute: typeof ApiDisplayBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homes': {
      id: '/api/homes'
      path: '/api/homes'
      fullPath: '/api/homes'
      preLoaderRoute: typeof ApiHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series': {
      id: '/api/series'
      path: '/api/series'
      fullPath: '/api/series'
      preLoaderRoute: typeof ApiSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tou': {
      id: '/api/tou'
      path: '/api/tou'
      fullPath: '/api/tou'
      preLoaderRoute: typeof ApiTouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$metric': {
      id: '/graphs/$metric'
      path: '/graphs/$metric'
      fullPath: '/graphs/$metric'
      preLoaderRoute: typeof GraphsMetricRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAlertsSettingsRoute: ApiAlertsSettingsRoute,
  ApiCostRoute: ApiCostRoute,
  ApiCredentialsRoute: ApiCredentialsRoute,
  ApiDisplayRoute: ApiDisplayRoute,
  ApiDisplayBackgroundRoute: ApiDisplayBackgroundRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiHomesRoute: ApiHomesRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiSeriesRoute: ApiSeriesRoute,
  ApiTouRoute: ApiTouRoute,
  GraphsMetricRoute: GraphsMetricRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
