/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiAlertsSettingsRouteImport } from './routes/api/alerts-settings'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiCredentialsRouteImport } from './routes/api/credentials'
import { Route as ApiDisplayRouteImport } from './routes/api/display'
import { Route as ApiDisplayBackgroundRouteImport } from './routes/api/display-background'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHomesRouteImport } from './routes/api/homes'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiRingRouteImport } from './routes/api/ring'
import { Route as ApiSeriesRouteImport } from './routes/api/series'
import { Route as ApiTouRouteImport } from './routes/api/tou'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed/account/index'
import { Route as AuthedAccountPasswordRouteImport } from './routes/_authed/account/password'
import { Route as AuthedGraphsMetricRouteImport } from './routes/_authed/graphs/$metric'
import { Route as ApiAdminAuditRouteImport } from './routes/api/admin/audit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRtcSplatRouteImport } from './routes/api/rtc.$'
import { Route as ApiAdminUsersUserIdRevokeSessionsRouteImport } from './routes/api/admin/users.$userId.revoke-sessions'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsSettingsRoute = ApiAlertsSettingsRouteImport.update({
  id: '/api/alerts-settings',
  path: '/api/alerts-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCredentialsRoute = ApiCredentialsRouteImport.update({
  id: '/api/credentials',
  path: '/api/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplayRoute = ApiDisplayRouteImport.update({
  id: '/api/display',
  path: '/api/display',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplayBackgroundRoute = ApiDisplayBackgroundRouteImport.update({
  id: '/api/display-background',
  path: '/api/display-background',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomesRoute = ApiHomesRouteImport.update({
  id: '/api/homes',
  path: '/api/homes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRingRoute = ApiRingRouteImport.update({
  id: '/api/ring',
  path: '/api/ring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesRoute = ApiSeriesRouteImport.update({
  id: '/api/series',
  path: '/api/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTouRoute = ApiTouRouteImport.update({
  id: '/api/tou',
  path: '/api/tou',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountPasswordRoute = AuthedAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGraphsMetricRoute = AuthedGraphsMetricRouteImport.update({
  id: '/graphs/$metric',
  path: '/graphs/$metric',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAdminAuditRoute = ApiAdminAuditRouteImport.update({
  id: '/api/admin/audit',
  path: '/api/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcSplatRoute = ApiRtcSplatRouteImport.update({
  id: '/api/rtc/$',
  path: '/api/rtc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersUserIdRevokeSessionsRoute =
  ApiAdminUsersUserIdRevokeSessionsRouteImport.update({
    id: '/api/admin/users/$userId/revoke-sessions',
    path: '/api/admin/users/$userId/revoke-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/signin': typeof SigninRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/ring': typeof ApiRingRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/graphs/$metric': typeof AuthedGraphsMetricRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rtc/$': typeof ApiRtcSplatRoute
  '/account/': typeof AuthedAccountIndexRoute
  '/api/admin/users/$userId/revoke-sessions': typeof ApiAdminUsersUserIdRevokeSessionsRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/ring': typeof ApiRingRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/': typeof AuthedIndexRoute
  '/account/password': typeof AuthedAccountPasswordRoute
  '/graphs/$metric': typeof AuthedGraphsMetricRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rtc/$': typeof ApiRtcSplatRoute
  '/account': typeof AuthedAccountIndexRoute
  '/api/admin/users/$userId/revoke-sessions': typeof ApiAdminUsersUserIdRevokeSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/ring': typeof ApiRingRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/account/password': typeof AuthedAccountPasswordRoute
  '/_authed/graphs/$metric': typeof AuthedGraphsMetricRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rtc/$': typeof ApiRtcSplatRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
  '/api/admin/users/$userId/revoke-sessions': typeof ApiAdminUsersUserIdRevokeSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/ring'
    | '/api/series'
    | '/api/tou'
    | '/account/password'
    | '/graphs/$metric'
    | '/api/admin/audit'
    | '/api/auth/$'
    | '/api/rtc/$'
    | '/account/'
    | '/api/admin/users/$userId/revoke-sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/ring'
    | '/api/series'
    | '/api/tou'
    | '/'
    | '/account/password'
    | '/graphs/$metric'
    | '/api/admin/audit'
    | '/api/auth/$'
    | '/api/rtc/$'
    | '/account'
    | '/api/admin/users/$userId/revoke-sessions'
  id:
    | '__root__'
    | '/_authed'
    | '/signin'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/ring'
    | '/api/series'
    | '/api/tou'
    | '/_authed/'
    | '/_authed/account/password'
    | '/_authed/graphs/$metric'
    | '/api/admin/audit'
    | '/api/auth/$'
    | '/api/rtc/$'
    | '/_authed/account/'
    | '/api/admin/users/$userId/revoke-sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAlertsSettingsRoute: typeof ApiAlertsSettingsRoute
  ApiCostRoute: typeof ApiCostRoute
  ApiCredentialsRoute: typeof ApiCredentialsRoute
  ApiDisplayRoute: typeof ApiDisplayRoute
  ApiDisplayBackgroundRoute: typeof ApiDisplayBackgroundRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiHomesRoute: typeof ApiHomesRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiRingRoute: typeof ApiRingRoute
  ApiSeriesRoute: typeof ApiSeriesRoute
  ApiTouRoute: typeof ApiTouRoute
  ApiAdminAuditRoute: typeof ApiAdminAuditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRtcSplatRoute: typeof ApiRtcSplatRoute
  ApiAdminUsersUserIdRevokeSessionsRoute: typeof ApiAdminUsersUserIdRevokeSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts-settings': {
      id: '/api/alerts-settings'
      path: '/api/alerts-settings'
      fullPath: '/api/alerts-settings'
      preLoaderRoute: typeof ApiAlertsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials': {
      id: '/api/credentials'
      path: '/api/credentials'
      fullPath: '/api/credentials'
      preLoaderRoute: typeof ApiCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/display': {
      id: '/api/display'
      path: '/api/display'
      fullPath: '/api/display'
      preLoaderRoute: typeof ApiDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/display-background': {
      id: '/api/display-background'
      path: '/api/display-background'
      fullPath: '/api/display-background'
      preLoaderRoute: typeof ApiDisplayBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homes': {
      id: '/api/homes'
      path: '/api/homes'
      fullPath: '/api/homes'
      preLoaderRoute: typeof ApiHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ring': {
      id: '/api/ring'
      path: '/api/ring'
      fullPath: '/api/ring'
      preLoaderRoute: typeof ApiRingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series': {
      id: '/api/series'
      path: '/api/series'
      fullPath: '/api/series'
      preLoaderRoute: typeof ApiSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tou': {
      id: '/api/tou'
      path: '/api/tou'
      fullPath: '/api/tou'
      preLoaderRoute: typeof ApiTouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/password': {
      id: '/_authed/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthedAccountPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/graphs/$metric': {
      id: '/_authed/graphs/$metric'
      path: '/graphs/$metric'
      fullPath: '/graphs/$metric'
      preLoaderRoute: typeof AuthedGraphsMetricRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/admin/audit': {
      id: '/api/admin/audit'
      path: '/api/admin/audit'
      fullPath: '/api/admin/audit'
      preLoaderRoute: typeof ApiAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc/$': {
      id: '/api/rtc/$'
      path: '/api/rtc/$'
      fullPath: '/api/rtc/$'
      preLoaderRoute: typeof ApiRtcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$userId/revoke-sessions': {
      id: '/api/admin/users/$userId/revoke-sessions'
      path: '/api/admin/users/$userId/revoke-sessions'
      fullPath: '/api/admin/users/$userId/revoke-sessions'
      preLoaderRoute: typeof ApiAdminUsersUserIdRevokeSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountPasswordRoute: typeof AuthedAccountPasswordRoute
  AuthedGraphsMetricRoute: typeof AuthedGraphsMetricRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountPasswordRoute: AuthedAccountPasswordRoute,
  AuthedGraphsMetricRoute: AuthedGraphsMetricRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAlertsSettingsRoute: ApiAlertsSettingsRoute,
  ApiCostRoute: ApiCostRoute,
  ApiCredentialsRoute: ApiCredentialsRoute,
  ApiDisplayRoute: ApiDisplayRoute,
  ApiDisplayBackgroundRoute: ApiDisplayBackgroundRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiHomesRoute: ApiHomesRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiRingRoute: ApiRingRoute,
  ApiSeriesRoute: ApiSeriesRoute,
  ApiTouRoute: ApiTouRoute,
  ApiAdminAuditRoute: ApiAdminAuditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRtcSplatRoute: ApiRtcSplatRoute,
  ApiAdminUsersUserIdRevokeSessionsRoute:
    ApiAdminUsersUserIdRevokeSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
