/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedFlowRouteImport } from './routes/_authed/flow'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiAlertsSettingsRouteImport } from './routes/api/alerts-settings'
import { Route as ApiAuthConfigRouteImport } from './routes/api/auth-config'
import { Route as ApiCostRouteImport } from './routes/api/cost'
import { Route as ApiCredentialsRouteImport } from './routes/api/credentials'
import { Route as ApiDisplayRouteImport } from './routes/api/display'
import { Route as ApiDisplayBackgroundRouteImport } from './routes/api/display-background'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHomesRouteImport } from './routes/api/homes'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiSeriesRouteImport } from './routes/api/series'
import { Route as ApiTouRouteImport } from './routes/api/tou'
import { Route as AuthedAccountIndexRouteImport } from './routes/_authed/account/index'
import { Route as AuthedAccountPinRouteImport } from './routes/_authed/account/pin'
import { Route as AuthedGraphsMetricRouteImport } from './routes/_authed/graphs/$metric'
import { Route as ApiAdminAuditRouteImport } from './routes/api/admin/audit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersUserIdRevokeSessionsRouteImport } from './routes/api/admin/users.$userId.revoke-sessions'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFlowRoute = AuthedFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsSettingsRoute = ApiAlertsSettingsRouteImport.update({
  id: '/api/alerts-settings',
  path: '/api/alerts-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfigRoute = ApiAuthConfigRouteImport.update({
  id: '/api/auth-config',
  path: '/api/auth-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api/cost',
  path: '/api/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCredentialsRoute = ApiCredentialsRouteImport.update({
  id: '/api/credentials',
  path: '/api/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplayRoute = ApiDisplayRouteImport.update({
  id: '/api/display',
  path: '/api/display',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplayBackgroundRoute = ApiDisplayBackgroundRouteImport.update({
  id: '/api/display-background',
  path: '/api/display-background',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomesRoute = ApiHomesRouteImport.update({
  id: '/api/homes',
  path: '/api/homes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesRoute = ApiSeriesRouteImport.update({
  id: '/api/series',
  path: '/api/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTouRoute = ApiTouRouteImport.update({
  id: '/api/tou',
  path: '/api/tou',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountIndexRoute = AuthedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountPinRoute = AuthedAccountPinRouteImport.update({
  id: '/account/pin',
  path: '/account/pin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGraphsMetricRoute = AuthedGraphsMetricRouteImport.update({
  id: '/graphs/$metric',
  path: '/graphs/$metric',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAdminAuditRoute = ApiAdminAuditRouteImport.update({
  id: '/api/admin/audit',
  path: '/api/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersUserIdRevokeSessionsRoute =
  ApiAdminUsersUserIdRevokeSessionsRouteImport.update({
    id: '/api/admin/users/$userId/revoke-sessions',
    path: '/api/admin/users/$userId/revoke-sessions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/flow': typeof AuthedFlowRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/account/pin': typeof AuthedAccountPinRoute
  '/graphs/$metric': typeof AuthedGraphsMetricRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/': typeof AuthedAccountIndexRoute
  '/api/admin/users/$userId/revoke-sessions': typeof ApiAdminUsersUserIdRevokeSessionsRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/flow': typeof AuthedFlowRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/': typeof AuthedIndexRoute
  '/account/pin': typeof AuthedAccountPinRoute
  '/graphs/$metric': typeof AuthedGraphsMetricRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account': typeof AuthedAccountIndexRoute
  '/api/admin/users/$userId/revoke-sessions': typeof ApiAdminUsersUserIdRevokeSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/flow': typeof AuthedFlowRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/alerts-settings': typeof ApiAlertsSettingsRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/cost': typeof ApiCostRoute
  '/api/credentials': typeof ApiCredentialsRoute
  '/api/display': typeof ApiDisplayRoute
  '/api/display-background': typeof ApiDisplayBackgroundRoute
  '/api/health': typeof ApiHealthRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/homes': typeof ApiHomesRoute
  '/api/live': typeof ApiLiveRoute
  '/api/series': typeof ApiSeriesRoute
  '/api/tou': typeof ApiTouRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/account/pin': typeof AuthedAccountPinRoute
  '/_authed/graphs/$metric': typeof AuthedGraphsMetricRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/account/': typeof AuthedAccountIndexRoute
  '/api/admin/users/$userId/revoke-sessions': typeof ApiAdminUsersUserIdRevokeSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/dashboard'
    | '/flow'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/auth-config'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/series'
    | '/api/tou'
    | '/account/pin'
    | '/graphs/$metric'
    | '/api/admin/audit'
    | '/api/auth/$'
    | '/account/'
    | '/api/admin/users/$userId/revoke-sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/dashboard'
    | '/flow'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/auth-config'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/series'
    | '/api/tou'
    | '/'
    | '/account/pin'
    | '/graphs/$metric'
    | '/api/admin/audit'
    | '/api/auth/$'
    | '/account'
    | '/api/admin/users/$userId/revoke-sessions'
  id:
    | '__root__'
    | '/_authed'
    | '/signin'
    | '/_authed/dashboard'
    | '/_authed/flow'
    | '/api/alerts'
    | '/api/alerts-settings'
    | '/api/auth-config'
    | '/api/cost'
    | '/api/credentials'
    | '/api/display'
    | '/api/display-background'
    | '/api/health'
    | '/api/history'
    | '/api/homes'
    | '/api/live'
    | '/api/series'
    | '/api/tou'
    | '/_authed/'
    | '/_authed/account/pin'
    | '/_authed/graphs/$metric'
    | '/api/admin/audit'
    | '/api/auth/$'
    | '/_authed/account/'
    | '/api/admin/users/$userId/revoke-sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAlertsSettingsRoute: typeof ApiAlertsSettingsRoute
  ApiAuthConfigRoute: typeof ApiAuthConfigRoute
  ApiCostRoute: typeof ApiCostRoute
  ApiCredentialsRoute: typeof ApiCredentialsRoute
  ApiDisplayRoute: typeof ApiDisplayRoute
  ApiDisplayBackgroundRoute: typeof ApiDisplayBackgroundRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiHomesRoute: typeof ApiHomesRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiSeriesRoute: typeof ApiSeriesRoute
  ApiTouRoute: typeof ApiTouRoute
  ApiAdminAuditRoute: typeof ApiAdminAuditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAdminUsersUserIdRevokeSessionsRoute: typeof ApiAdminUsersUserIdRevokeSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/flow': {
      id: '/_authed/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof AuthedFlowRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts-settings': {
      id: '/api/alerts-settings'
      path: '/api/alerts-settings'
      fullPath: '/api/alerts-settings'
      preLoaderRoute: typeof ApiAlertsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-config': {
      id: '/api/auth-config'
      path: '/api/auth-config'
      fullPath: '/api/auth-config'
      preLoaderRoute: typeof ApiAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cost': {
      id: '/api/cost'
      path: '/api/cost'
      fullPath: '/api/cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials': {
      id: '/api/credentials'
      path: '/api/credentials'
      fullPath: '/api/credentials'
      preLoaderRoute: typeof ApiCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/display': {
      id: '/api/display'
      path: '/api/display'
      fullPath: '/api/display'
      preLoaderRoute: typeof ApiDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/display-background': {
      id: '/api/display-background'
      path: '/api/display-background'
      fullPath: '/api/display-background'
      preLoaderRoute: typeof ApiDisplayBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homes': {
      id: '/api/homes'
      path: '/api/homes'
      fullPath: '/api/homes'
      preLoaderRoute: typeof ApiHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series': {
      id: '/api/series'
      path: '/api/series'
      fullPath: '/api/series'
      preLoaderRoute: typeof ApiSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tou': {
      id: '/api/tou'
      path: '/api/tou'
      fullPath: '/api/tou'
      preLoaderRoute: typeof ApiTouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account/': {
      id: '/_authed/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthedAccountIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/pin': {
      id: '/_authed/account/pin'
      path: '/account/pin'
      fullPath: '/account/pin'
      preLoaderRoute: typeof AuthedAccountPinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/graphs/$metric': {
      id: '/_authed/graphs/$metric'
      path: '/graphs/$metric'
      fullPath: '/graphs/$metric'
      preLoaderRoute: typeof AuthedGraphsMetricRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/admin/audit': {
      id: '/api/admin/audit'
      path: '/api/admin/audit'
      fullPath: '/api/admin/audit'
      preLoaderRoute: typeof ApiAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$userId/revoke-sessions': {
      id: '/api/admin/users/$userId/revoke-sessions'
      path: '/api/admin/users/$userId/revoke-sessions'
      fullPath: '/api/admin/users/$userId/revoke-sessions'
      preLoaderRoute: typeof ApiAdminUsersUserIdRevokeSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFlowRoute: typeof AuthedFlowRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountPinRoute: typeof AuthedAccountPinRoute
  AuthedGraphsMetricRoute: typeof AuthedGraphsMetricRoute
  AuthedAccountIndexRoute: typeof AuthedAccountIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFlowRoute: AuthedFlowRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountPinRoute: AuthedAccountPinRoute,
  AuthedGraphsMetricRoute: AuthedGraphsMetricRoute,
  AuthedAccountIndexRoute: AuthedAccountIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAlertsSettingsRoute: ApiAlertsSettingsRoute,
  ApiAuthConfigRoute: ApiAuthConfigRoute,
  ApiCostRoute: ApiCostRoute,
  ApiCredentialsRoute: ApiCredentialsRoute,
  ApiDisplayRoute: ApiDisplayRoute,
  ApiDisplayBackgroundRoute: ApiDisplayBackgroundRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiHomesRoute: ApiHomesRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiSeriesRoute: ApiSeriesRoute,
  ApiTouRoute: ApiTouRoute,
  ApiAdminAuditRoute: ApiAdminAuditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAdminUsersUserIdRevokeSessionsRoute:
    ApiAdminUsersUserIdRevokeSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
